package de.servicehealth.epa4all.integration.bc.wiremock;

import com.icegreen.greenmail.util.GreenMail;
import com.icegreen.greenmail.util.ServerSetup;
import com.unboundid.ldap.listener.InMemoryDirectoryServer;
import com.unboundid.ldap.listener.InMemoryDirectoryServerConfig;
import com.unboundid.ldap.listener.InMemoryListenerConfig;
import com.unboundid.ldap.sdk.Entry;
import de.servicehealth.epa4all.common.profile.WireMockProfile;
import de.servicehealth.epa4all.integration.base.AbstractWiremockTest;
import de.servicehealth.epa4all.server.filetracker.FileEventSender;
import de.servicehealth.epa4all.server.kim.KimLdapConfig;
import de.servicehealth.epa4all.server.kim.KimSmtpConfig;
import de.servicehealth.epa4all.server.kim.SmtpConfig;
import de.servicehealth.epa4all.server.rest.EPrescriptionKimSender;
import de.servicehealth.epa4all.server.rest.EquipmentPrescription;
import de.servicehealth.utils.SSLUtils;
import io.quarkus.test.InjectMock;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.TestProfile;
import jakarta.inject.Inject;
import jakarta.mail.BodyPart;
import jakarta.mail.Message;
import jakarta.mail.Multipart;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.net.ssl.SSLContext;
import java.net.InetAddress;
import java.net.URL;
import java.util.Map;

import static com.github.tomakehurst.wiremock.common.ResourceUtil.getResource;
import static com.icegreen.greenmail.util.ServerSetup.PROTOCOL_SMTP;
import static de.servicehealth.utils.SSLUtils.KeyStoreType.JKS;
import static de.servicehealth.vau.VauClient.X_INSURANT_ID;
import static de.servicehealth.vau.VauClient.X_KONNEKTOR;
import static io.restassured.RestAssured.given;
import static jakarta.ws.rs.core.MediaType.APPLICATION_JSON;
import static org.hamcrest.Matchers.containsString;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SuppressWarnings("unused")
@QuarkusTest
@TestProfile(WireMockProfile.class)
public class KimPrescriptionIT extends AbstractWiremockTest {

    @InjectMock
    FileEventSender suppressJcrHandling;

    @Inject
    KimLdapConfig ldapConfig;

    @Inject
    KimSmtpConfig kimConfig;

    @Inject
    SmtpConfig smtpConfig;

    GreenMail greenMail;

    @BeforeEach
    void setUp() {
        greenMail = new GreenMail(new ServerSetup(smtpConfig.getPort(), null, PROTOCOL_SMTP));
        greenMail.start();
    }

    @AfterEach
    void tearDown() {
        greenMail.stop();
    }

    private InMemoryDirectoryServer startLdapServer(String practitionerName) throws Exception {
        URL resource = getResource(KimPrescriptionIT.class, "keystore");
        SSLContext sslContext = SSLUtils.createSSLContextBundle(resource.openStream(), "password", JKS).getSslContext();
        InMemoryListenerConfig listenerConfig = InMemoryListenerConfig.createLDAPSConfig(
            "test-ssl",
            InetAddress.getByName("localhost"),
            ldapConfig.getLdapPort(),
            sslContext.getServerSocketFactory(),
            sslContext.getSocketFactory(),
            true,
            true
        );
        InMemoryDirectoryServerConfig config = new InMemoryDirectoryServerConfig("dc=data,dc=vzd");
        config.setListenerConfigs(listenerConfig);
        config.setSchema(null);

        InMemoryDirectoryServer server = new InMemoryDirectoryServer(config);
        server.add(new Entry(
            "dn: dc=data,dc=vzd",
            "objectClass: top",
            "objectClass: domain",
            "dc: data"
        ));
        server.add(new Entry(
            "dn: cn=Tanja Müller,dc=data,dc=vzd",
            "objectClass: top",
            "objectClass: person",
            "objectClass: organizationalPerson",
            "objectClass: inetOrgPerson",
            "cn: Tanja Müller",
            "sn: Müller",
            "displayName: " + practitionerName,
            "rfc822mailbox: dr.mueller@praxis.kim.telematik",
            "professionOID: 1.2.276.0.76.4.54"
        ));
        return server;
    }

    @Test
    public void prescriptionSentToKim() throws Exception {
        startPrescriptionFlow(true, 200, "OK");
        assertReceivedContent("Ibuprofen Atid 600mg 10 ST");
    }

    @Test
    public void prescriptionWasNotSentToKim() throws Exception {
        startPrescriptionFlow(false, 404, "not found");
    }

    private void startPrescriptionFlow(boolean positiveFlow, int expectedStatus, String expectedBodyPart) throws Exception {
        String practitionerName = "Praxis Dr. Müller";
        try (InMemoryDirectoryServer ldapServer = startLdapServer(practitionerName)) {
            ldapServer.startListening();
            String telematikId = "1-SMC-B-Testkarte--883110000162363";
            String kvnr = "X110587452";
            prepareInsurantFiles(telematikId, kvnr);

            String epaBundleBase64 = "eyJyZXNvdXJjZVR5cGUiOiJCdW5kbGUiLCJpZCI6IjAxOWQyZGUzLTMwMTQtNzEyNS04MDcxLWNjN2Y2ZTFjNGRjYyIsInR5cGUiOiJzZWFyY2hzZXQiLCJ0b3RhbCI6MiwibGluayI6W3sicmVsYXRpb24iOiJzZWxmIiwidXJsIjoiL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyLyRtZWRpY2F0aW9uLWxpc3Q/X2NvdW50PTEwIn0seyJyZWxhdGlvbiI6ImZpcnN0IiwidXJsIjoiL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyLyRtZWRpY2F0aW9uLWxpc3Q/X2NvdW50PTEwIn1dLCJlbnRyeSI6W3siZnVsbFVybCI6Imh0dHA6Ly9lcGE0YWxsL2VwYS9wYXRpZW50L2FwaS92MS9maGlyL1BhdGllbnQvMDE5YzFlOTItNDYxYi03Mjk4LTgwZDUtNDY2YmYxYzY2NGE1IiwicmVzb3VyY2UiOnsicmVzb3VyY2VUeXBlIjoiUGF0aWVudCIsImlkIjoiMDE5YzFlOTItNDYxYi03Mjk4LTgwZDUtNDY2YmYxYzY2NGE1IiwibWV0YSI6eyJwcm9maWxlIjpbImh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS9TdHJ1Y3R1cmVEZWZpbml0aW9uL2VwYS1wYXRpZW50fDEuMy4wIl0sInZlcnNpb25JZCI6IjEiLCJsYXN0VXBkYXRlZCI6IjIwMjYtMDItMDJUMTM6Mzc6MDguNjM1NzEzWiJ9LCJpZGVudGlmaWVyIjpbeyJzeXN0ZW0iOiJodHRwOi8vZmhpci5kZS9zaWQvZ2t2L2t2aWQtMTAiLCJ2YWx1ZSI6IlgxMTA2MjQwMDYifV0sIm5hbWUiOlt7InVzZSI6Im9mZmljaWFsIiwiZmFtaWx5IjoiRCVDMyVBNW1tZXItJUMzJTk4cnN0ZWQiLCJnaXZlbiI6WyJMdWthcyJdfSx7InVzZSI6Im1haWRlbiIsImZhbWlseSI6IkQlQzMlQTVtbWVyLSVDMyU5OHJzdGVkIiwiX2ZhbWlseSI6eyJleHRlbnNpb24iOlt7InVybCI6Imh0dHA6Ly9obDcub3JnL2ZoaXIvU3RydWN0dXJlRGVmaW5pdGlvbi9odW1hbm5hbWUtb3duLW5hbWUiLCJ2YWx1ZVN0cmluZyI6IkQlQzMlQTVtbWVyLSVDMyU5OHJzdGVkIn1dfX1dLCJnZW5kZXIiOiJtYWxlIiwiYmlydGhEYXRlIjoiMTk4NS0wNS0xNiJ9LCJzZWFyY2giOnsibW9kZSI6Im1hdGNoIn19LHsiZnVsbFVybCI6Imh0dHA6Ly9lcGE0YWxsL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyL01lZGljYXRpb25TdGF0ZW1lbnQvMDE5YzFlOTItNDU4OC03Mjc1LTgwNjAtZDgxMzVjMGJjNWY3IiwicmVzb3VyY2UiOnsiZGF0ZUFzc2VydGVkIjoiMjAyNS0wMi0xNyIsImRlcml2ZWRGcm9tIjpbeyJyZWZlcmVuY2UiOiJNZWRpY2F0aW9uUmVxdWVzdC81YTExMzYxNC1lZTVmLTRkNTYtYmI4Zi03OTc5OWIwZmY5ODIifV0sImRvc2FnZSI6W3sidGV4dCI6IjAtMS0wIn1dLCJlZmZlY3RpdmVQZXJpb2QiOnsic3RhcnQiOiIyMDI1LTAyLTE3In0sImV4dGVuc2lvbiI6W3sidXJsIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9jb250ZXh0LWV4dGVuc2lvbiIsInZhbHVlQ29kZSI6IlBSRVNDUklQVElPTiJ9LHsidXJsIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9yeC1wcmVzY3JpcHRpb24tcHJvY2Vzcy1pZGVudGlmaWVyLWV4dGVuc2lvbiIsInZhbHVlSWRlbnRpZmllciI6eyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9zaWQvcngtcHJlc2NyaXB0aW9uLXByb2Nlc3MtaWRlbnRpZmllciIsInZhbHVlIjoiMTYwLjAwMC4xMDYuODc4LjI0MS45NV8yMDI1MDIxNyJ9fV0sImlkIjoiMDE5YzFlOTItNDU4OC03Mjc1LTgwNjAtZDgxMzVjMGJjNWY3IiwibWVkaWNhdGlvblJlZmVyZW5jZSI6eyJyZWZlcmVuY2UiOiJNZWRpY2F0aW9uL2I5MDYxZGNmLWFlMDAtNDcyYy04MmI1LWQ4ZjI5MTA0YjM1YyJ9LCJtZXRhIjp7Imxhc3RVcGRhdGVkIjoiMjAyNi0wMi0wMlQxMzozNzowOC40ODg2MzZaIiwicHJvZmlsZSI6WyJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL2VwYS1tZWRpY2F0aW9uLXN0YXRlbWVudHwxLjMuMCJdLCJ2ZXJzaW9uSWQiOiIxIn0sInJlc291cmNlVHlwZSI6Ik1lZGljYXRpb25TdGF0ZW1lbnQiLCJzdGF0dXMiOiJpbnRlbmRlZCIsInN1YmplY3QiOnsiaWRlbnRpZmllciI6eyJzeXN0ZW0iOiJodHRwOi8vZmhpci5kZS9zaWQvZ2t2L2t2aWQtMTAiLCJ2YWx1ZSI6IlgxMTA2MjQwMDYifX19LCJzZWFyY2giOnsibW9kZSI6Im1hdGNoIn19LHsiZnVsbFVybCI6Imh0dHA6Ly9lcGE0YWxsL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyL01lZGljYXRpb24vYjkwNjFkY2YtYWUwMC00NzJjLTgyYjUtZDhmMjkxMDRiMzVjIiwicmVzb3VyY2UiOnsicmVzb3VyY2VUeXBlIjoiTWVkaWNhdGlvbiIsImlkIjoiYjkwNjFkY2YtYWUwMC00NzJjLTgyYjUtZDhmMjkxMDRiMzVjIiwibWV0YSI6eyJwcm9maWxlIjpbImh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vZXBhLW1lZGljYXRpb258MS4wLjMiXSwibGFzdFVwZGF0ZWQiOiIyMDI1LTAyLTE3VDA5OjQ3OjI5LjAxNjc1N1oifSwiZXh0ZW5zaW9uIjpbeyJ1cmwiOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL2RydWctY2F0ZWdvcnktZXh0ZW5zaW9uIiwidmFsdWVDb2RpbmciOnsic3lzdGVtIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vQ29kZVN5c3RlbS9lcGEtZHJ1Zy1jYXRlZ29yeS1jcyIsImNvZGUiOiIwMCJ9fSx7InVybCI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vbWVkaWNhdGlvbi1pZC12YWNjaW5lLWV4dGVuc2lvbiIsInZhbHVlQm9vbGVhbiI6ZmFsc2V9LHsidXJsIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9yeC1wcmVzY3JpcHRpb24tcHJvY2Vzcy1pZGVudGlmaWVyLWV4dGVuc2lvbiIsInZhbHVlSWRlbnRpZmllciI6eyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9zaWQvcngtcHJlc2NyaXB0aW9uLXByb2Nlc3MtaWRlbnRpZmllciIsInZhbHVlIjoiMTYwLjAwMC4xMDYuODc4LjI0MS45NV8yMDI1MDIxNyJ9fV0sImNvZGUiOnsiY29kaW5nIjpbeyJzeXN0ZW0iOiJodHRwOi8vZmhpci5kZS9Db2RlU3lzdGVtL2lmYS9wem4iLCJjb2RlIjoiMDAwMjc5NTAifV0sInRleHQiOiJJYnVwcm9mZW4gQXRpZCA2MDBtZyAxMCBTVCJ9LCJmb3JtIjp7ImNvZGluZyI6W3sic3lzdGVtIjoiaHR0cHM6Ly9maGlyLmtidi5kZS9Db2RlU3lzdGVtL0tCVl9DU19TRkhJUl9LQlZfREFSUkVJQ0hVTkdTRk9STSIsImNvZGUiOiJGVEEifV19LCJhbW91bnQiOnsibnVtZXJhdG9yIjp7ImV4dGVuc2lvbiI6W3sidXJsIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9tZWRpY2F0aW9uLXBhY2thZ2luZy1zaXplLWV4dGVuc2lvbiIsInZhbHVlU3RyaW5nIjoiMSJ9XSwidW5pdCI6IlBha2V0Iiwic3lzdGVtIjoiaHR0cDovL3VuaXRzb2ZtZWFzdXJlLm9yZyIsImNvZGUiOiJ7UGFja2FnZX0ifSwiZGVub21pbmF0b3IiOnsidmFsdWUiOjF9fSwiaWRlbnRpZmllciI6W3sic3lzdGVtIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vc2lkL2VwYS1tZWRpY2F0aW9uLXVuaXF1ZS1pZGVudGlmaWVyIiwidmFsdWUiOiI5MEJFNTkwOTRENkY5NTc5NjJDMDg2RUJBODcxNzEzNEIwNzE4NkM2NUUyMUJGQjFGQkVDM0QzQkRBMEM3RENGIn0seyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9zaWQvcngtb3JpZ2luYXRvci1wcm9jZXNzLWlkZW50aWZpZXIiLCJ2YWx1ZSI6ImY0ZDM2ZGRlLTViMWMtNGRkMi04M2Q1LTI0YzUzZWIzOGRhYV8xNjAuMDAwLjEwNi44NzguMjQxLjk1In1dLCJzdGF0dXMiOiJpbmFjdGl2ZSJ9LCJzZWFyY2giOnsibW9kZSI6Im1hdGNoIn19LHsiZnVsbFVybCI6Imh0dHA6Ly9lcGE0YWxsL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyL01lZGljYXRpb25SZXF1ZXN0LzVhMTEzNjE0LWVlNWYtNGQ1Ni1iYjhmLTc5Nzk5YjBmZjk4MiIsInJlc291cmNlIjp7InJlc291cmNlVHlwZSI6Ik1lZGljYXRpb25SZXF1ZXN0IiwiaWQiOiI1YTExMzYxNC1lZTVmLTRkNTYtYmI4Zi03OTc5OWIwZmY5ODIiLCJtZXRhIjp7InByb2ZpbGUiOlsiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9lcGEtbWVkaWNhdGlvbi1yZXF1ZXN0fDEuMC4zIl0sImxhc3RVcGRhdGVkIjoiMjAyNS0wMi0xN1QwOTo0NzoyOS4wMzUzMDVaIn0sImV4dGVuc2lvbiI6W3sidXJsIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9tdWx0aXBsZS1wcmVzY3JpcHRpb24tZXh0ZW5zaW9uIiwiZXh0ZW5zaW9uIjpbeyJ1cmwiOiJpbmRpY2F0b3IiLCJ2YWx1ZUJvb2xlYW4iOmZhbHNlfV19XSwic3RhdHVzIjoiYWN0aXZlIiwiaW50ZW50IjoiZmlsbGVyLW9yZGVyIiwibWVkaWNhdGlvblJlZmVyZW5jZSI6eyJyZWZlcmVuY2UiOiJNZWRpY2F0aW9uL2I5MDYxZGNmLWFlMDAtNDcyYy04MmI1LWQ4ZjI5MTA0YjM1YyJ9LCJzdWJqZWN0Ijp7ImlkZW50aWZpZXIiOnsic3lzdGVtIjoiaHR0cDovL2ZoaXIuZGUvc2lkL2drdi9rdmlkLTEwIiwidmFsdWUiOiJYMTEwNjI0MDA2In19LCJhdXRob3JlZE9uIjoiMjAyNS0wMi0xNyIsImRvc2FnZUluc3RydWN0aW9uIjpbeyJ0ZXh0IjoiMC0xLTAifV0sImRpc3BlbnNlUmVxdWVzdCI6eyJxdWFudGl0eSI6eyJ2YWx1ZSI6MSwic3lzdGVtIjoiaHR0cDovL3VuaXRzb2ZtZWFzdXJlLm9yZyIsImNvZGUiOiJ7UGFja2FnZX0ifX0sInN1YnN0aXR1dGlvbiI6eyJhbGxvd2VkQm9vbGVhbiI6dHJ1ZX0sImlkZW50aWZpZXIiOlt7InN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL3NpZC9yeC1wcmVzY3JpcHRpb24tcHJvY2Vzcy1pZGVudGlmaWVyIiwidmFsdWUiOiIxNjAuMDAwLjEwNi44NzguMjQxLjk1XzIwMjUwMjE3In0seyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9zaWQvcngtb3JpZ2luYXRvci1wcm9jZXNzLWlkZW50aWZpZXIiLCJ2YWx1ZSI6IjQ0ZmU2NzE3LWQwNzktNDhjNC1iYTliLWVlZWY3NDM4MmU1YV8xNjAuMDAwLjEwNi44NzguMjQxLjk1In1dLCJyZXF1ZXN0ZXIiOnsicmVmZXJlbmNlIjoiUHJhY3RpdGlvbmVyUm9sZS9iMTNjZDEyYS1jZjAwLTRlN2QtYWJmYi1iNDdjNjU1NjE2ZGQifX0sInNlYXJjaCI6eyJtb2RlIjoibWF0Y2gifX0seyJmdWxsVXJsIjoiaHR0cDovL2VwYTRhbGwvZXBhL21lZGljYXRpb24vYXBpL3YxL2ZoaXIvUHJhY3RpdGlvbmVyUm9sZS9iMTNjZDEyYS1jZjAwLTRlN2QtYWJmYi1iNDdjNjU1NjE2ZGQiLCJyZXNvdXJjZSI6eyJyZXNvdXJjZVR5cGUiOiJQcmFjdGl0aW9uZXJSb2xlIiwibWV0YSI6eyJwcm9maWxlIjpbImh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2RpcmVjdG9yeS9TdHJ1Y3R1cmVEZWZpbml0aW9uL1ByYWN0aXRpb25lclJvbGVEaXJlY3RvcnkiXSwidGFnIjpbeyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9kaXJlY3RvcnkvQ29kZVN5c3RlbS9PcmlnaW4iLCJjb2RlIjoibGRhcCJ9XSwibGFzdFVwZGF0ZWQiOiIyMDI1LTAyLTE3VDA5OjQ3OjI3LjM5MjM4OVoifSwiaWQiOiJiMTNjZDEyYS1jZjAwLTRlN2QtYWJmYi1iNDdjNjU1NjE2ZGQiLCJwcmFjdGl0aW9uZXIiOnsicmVmZXJlbmNlIjoiUHJhY3RpdGlvbmVyL2UyMmEwNWIzLTBjZTMtNGNmYi1hYmM0LWQ0MzY1ZTRiNTVjOCJ9LCJvcmdhbml6YXRpb24iOnsicmVmZXJlbmNlIjoiT3JnYW5pemF0aW9uL2E1ZmYwYTdlLTZkYmQtNGE3My04YmFlLWY1ZDljODkwZTFlNiJ9fSwic2VhcmNoIjp7Im1vZGUiOiJtYXRjaCJ9fSx7ImZ1bGxVcmwiOiJodHRwOi8vZXBhNGFsbC9lcGEvbWVkaWNhdGlvbi9hcGkvdjEvZmhpci9QcmFjdGl0aW9uZXIvZTIyYTA1YjMtMGNlMy00Y2ZiLWFiYzQtZDQzNjVlNGI1NWM4IiwicmVzb3VyY2UiOnsiaWQiOiJlMjJhMDViMy0wY2UzLTRjZmItYWJjNC1kNDM2NWU0YjU1YzgiLCJpZGVudGlmaWVyIjpbeyJzeXN0ZW0iOiJodHRwczovL2ZoaXIua2J2LmRlL05hbWluZ1N5c3RlbS9LQlZfTlNfQmFzZV9BTlIiLCJ0eXBlIjp7ImNvZGluZyI6W3siY29kZSI6IkxBTlIiLCJzeXN0ZW0iOiJodHRwOi8vdGVybWlub2xvZ3kuaGw3Lm9yZy9Db2RlU3lzdGVtL3YyLTAyMDMifV19LCJ2YWx1ZSI6IjEyMzQ1Njc4OSJ9LHsic3lzdGVtIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvc2lkL3RlbGVtYXRpay1pZCIsInZhbHVlIjoiMS1IQkEtVGVzdGthcnRlLTg4MzExMDAwMDE2MTY3NyJ9XSwibWV0YSI6eyJsYXN0VXBkYXRlZCI6IjIwMjYtMDItMDJUMTM6Mzc6MDguNTQ2ODIwWiIsInByb2ZpbGUiOlsiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZGlyZWN0b3J5L1N0cnVjdHVyZURlZmluaXRpb24vUHJhY3RpdGlvbmVyRGlyZWN0b3J5fDAuMTEuMTIiXSwidGFnIjpbeyJjb2RlIjoibGRhcCIsInN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2RpcmVjdG9yeS9Db2RlU3lzdGVtL09yaWdpbiJ9XX0sIm5hbWUiOlt7ImZhbWlseSI6IkRcdTAwZTV2aWQiLCJnaXZlbiI6WyJUYW5qYSBGcmVpZnJhdSJdLCJ0ZXh0IjoiVGFuamEgRnJlaWZyYXUgRFx1MDBlNXZpZCIsInVzZSI6Im9mZmljaWFsIn1dLCJyZXNvdXJjZVR5cGUiOiJQcmFjdGl0aW9uZXIifSwic2VhcmNoIjp7Im1vZGUiOiJtYXRjaCJ9fSx7ImZ1bGxVcmwiOiJodHRwOi8vZXBhNGFsbC9lcGEvbWVkaWNhdGlvbi9hcGkvdjEvZmhpci9Pcmdhbml6YXRpb24vYTVmZjBhN2UtNmRiZC00YTczLThiYWUtZjVkOWM4OTBlMWU2IiwicmVzb3VyY2UiOnsicmVzb3VyY2VUeXBlIjoiT3JnYW5pemF0aW9uIiwiaWQiOiJhNWZmMGE3ZS02ZGJkLTRhNzMtOGJhZS1mNWQ5Yzg5MGUxZTYiLCJtZXRhIjp7InByb2ZpbGUiOlsiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZGlyZWN0b3J5L1N0cnVjdHVyZURlZmluaXRpb24vT3JnYW5pemF0aW9uRGlyZWN0b3J5fDAuMTEuMTIiXSwidGFnIjpbeyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9kaXJlY3RvcnkvQ29kZVN5c3RlbS9PcmlnaW4iLCJjb2RlIjoibGRhcCJ9XSwibGFzdFVwZGF0ZWQiOiIyMDI1LTAyLTE3VDA5OjQ3OjI4Ljk4NDMxOVoifSwiaWRlbnRpZmllciI6W3sidHlwZSI6eyJjb2RpbmciOlt7InN5c3RlbSI6Imh0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL0NvZGVTeXN0ZW0vdjItMDIwMyIsImNvZGUiOiJCU05SIn1dfSwic3lzdGVtIjoiaHR0cHM6Ly9maGlyLmtidi5kZS9OYW1pbmdTeXN0ZW0vS0JWX05TX0Jhc2VfQlNOUiIsInZhbHVlIjoiMTIzNDU2Nzg5In0seyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9zaWQvdGVsZW1hdGlrLWlkIiwidmFsdWUiOiIxLVNNQy1CLVRlc3RrYXJ0ZS0tODgzMTEwMDAwMTYyMzYzIn1dLCJuYW1lIjoiUHJheGlzIFhlbmlhIEdyXHUwMGU0ZmluIGQnIEF1YmVydGluXHUwMGYzVEVTVC1PTkxZIiwidGVsZWNvbSI6W3sic3lzdGVtIjoicGhvbmUiLCJ2YWx1ZSI6IjAxNzM2MzIyNjIxIn1dLCJhZGRyZXNzIjpbeyJ0eXBlIjoiYm90aCIsImxpbmUiOlsiS2lyY2hzcGllbHN3ZWcgNiJdLCJjaXR5IjoiSGVpZGUiLCJwb3N0YWxDb2RlIjoiMjU3NDYiLCJjb3VudHJ5IjoiRCJ9XSwidHlwZSI6W3siY29kaW5nIjpbeyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9kaXJlY3RvcnkvQ29kZVN5c3RlbS9Pcmdhbml6YXRpb25Qcm9mZXNzaW9uT0lEIiwiY29kZSI6IjEuMi4yNzYuMC43Ni40LjUwIn1dfV19LCJzZWFyY2giOnsibW9kZSI6Im1hdGNoIn19LHsiZnVsbFVybCI6Imh0dHA6Ly9lcGE0YWxsL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyL1Byb3ZlbmFuY2UvMDE5YzFlOTItNDU5Yi03MjAyLTgwMTMtMjdmZTU4YTgyOWIzIiwicmVzb3VyY2UiOnsiYWN0aXZpdHkiOnsiY29kaW5nIjpbeyJjb2RlIjoiQ1JFQVRFIiwiZGlzcGxheSI6ImNyZWF0ZSIsInN5c3RlbSI6Imh0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL0NvZGVTeXN0ZW0vdjMtRGF0YU9wZXJhdGlvbiJ9XX0sImFnZW50IjpbeyJ0eXBlIjp7ImNvZGluZyI6W3siY29kZSI6ImF1dGhvciIsImRpc3BsYXkiOiJBdXRob3IiLCJzeXN0ZW0iOiJodHRwOi8vdGVybWlub2xvZ3kuaGw3Lm9yZy9Db2RlU3lzdGVtL3Byb3ZlbmFuY2UtcGFydGljaXBhbnQtdHlwZSJ9XX0sIndobyI6eyJpZGVudGlmaWVyIjp7InN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL3NpZC9lcGEtZmhpci1kYXRhLXNlcnZpY2UiLCJ2YWx1ZSI6Ik1FRElDQVRJT05TVkMifX19XSwiaWQiOiIwMTljMWU5Mi00NTliLTcyMDItODAxMy0yN2ZlNThhODI5YjMiLCJtZXRhIjp7Imxhc3RVcGRhdGVkIjoiMjAyNi0wMi0wMlQxMzozNzowOC41MDc1MTlaIiwicHJvZmlsZSI6WyJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEvU3RydWN0dXJlRGVmaW5pdGlvbi9lcGEtYWN0aXZpdHktcHJvdmVuYW5jZXwxLjMuMCJdLCJ2ZXJzaW9uSWQiOiIxIn0sInJlY29yZGVkIjoiMjAyNi0wMi0wMlQxMzozNzowOC41MDc1MzBaIiwicmVzb3VyY2VUeXBlIjoiUHJvdmVuYW5jZSIsInRhcmdldCI6W3sicmVmZXJlbmNlIjoiTWVkaWNhdGlvblN0YXRlbWVudC8wMTljMWU5Mi00NTg4LTcyNzUtODA2MC1kODEzNWMwYmM1ZjcvX2hpc3RvcnkvMSJ9XX0sInNlYXJjaCI6eyJtb2RlIjoibWF0Y2gifX0seyJmdWxsVXJsIjoiaHR0cDovL2VwYTRhbGwvZXBhL21lZGljYXRpb24vYXBpL3YxL2ZoaXIvTWVkaWNhdGlvblN0YXRlbWVudC8wMTljMWU5Mi00NTVhLTcxM2MtODBjOC1kNWFiNWNmZjE5NTUiLCJyZXNvdXJjZSI6eyJkYXRlQXNzZXJ0ZWQiOiIyMDI1LTAyLTE3IiwiZGVyaXZlZEZyb20iOlt7InJlZmVyZW5jZSI6Ik1lZGljYXRpb25SZXF1ZXN0LzcyMmI3OTA0LWNkMmUtNGZkOS1iZjE5LTFiNDRlZjVhZTgwZSJ9XSwiZG9zYWdlIjpbeyJ0ZXh0IjoiMC0xLTAifV0sImVmZmVjdGl2ZVBlcmlvZCI6eyJzdGFydCI6IjIwMjUtMDItMTcifSwiZXh0ZW5zaW9uIjpbeyJ1cmwiOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL2NvbnRleHQtZXh0ZW5zaW9uIiwidmFsdWVDb2RlIjoiUFJFU0NSSVBUSU9OIn0seyJ1cmwiOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL3J4LXByZXNjcmlwdGlvbi1wcm9jZXNzLWlkZW50aWZpZXItZXh0ZW5zaW9uIiwidmFsdWVJZGVudGlmaWVyIjp7InN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL3NpZC9yeC1wcmVzY3JpcHRpb24tcHJvY2Vzcy1pZGVudGlmaWVyIiwidmFsdWUiOiIxNjAuMDAwLjEwNi44NzguMjQwLjk4XzIwMjUwMjE3In19XSwiaWQiOiIwMTljMWU5Mi00NTVhLTcxM2MtODBjOC1kNWFiNWNmZjE5NTUiLCJtZWRpY2F0aW9uUmVmZXJlbmNlIjp7InJlZmVyZW5jZSI6Ik1lZGljYXRpb24vZmM0NjQ1MWQtNmFmOC00YWZiLTg4MGMtNTEwNGQ3YWJhZDgzIn0sIm1ldGEiOnsibGFzdFVwZGF0ZWQiOiIyMDI2LTAyLTAyVDEzOjM3OjA4LjQ0MjMyOFoiLCJwcm9maWxlIjpbImh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vZXBhLW1lZGljYXRpb24tc3RhdGVtZW50fDEuMy4wIl0sInZlcnNpb25JZCI6IjEifSwicmVzb3VyY2VUeXBlIjoiTWVkaWNhdGlvblN0YXRlbWVudCIsInN0YXR1cyI6ImludGVuZGVkIiwic3ViamVjdCI6eyJpZGVudGlmaWVyIjp7InN5c3RlbSI6Imh0dHA6Ly9maGlyLmRlL3NpZC9na3Yva3ZpZC0xMCIsInZhbHVlIjoiWDExMDYyNDAwNiJ9fX0sInNlYXJjaCI6eyJtb2RlIjoibWF0Y2gifX0seyJmdWxsVXJsIjoiaHR0cDovL2VwYTRhbGwvZXBhL21lZGljYXRpb24vYXBpL3YxL2ZoaXIvTWVkaWNhdGlvbi9mYzQ2NDUxZC02YWY4LTRhZmItODgwYy01MTA0ZDdhYmFkODMiLCJyZXNvdXJjZSI6eyJyZXNvdXJjZVR5cGUiOiJNZWRpY2F0aW9uIiwiaWQiOiJmYzQ2NDUxZC02YWY4LTRhZmItODgwYy01MTA0ZDdhYmFkODMiLCJtZXRhIjp7InByb2ZpbGUiOlsiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9lcGEtbWVkaWNhdGlvbnwxLjAuMyJdLCJsYXN0VXBkYXRlZCI6IjIwMjUtMDItMTdUMDk6NDc6MjcuNDAyNzEwWiJ9LCJleHRlbnNpb24iOlt7InVybCI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vZHJ1Zy1jYXRlZ29yeS1leHRlbnNpb24iLCJ2YWx1ZUNvZGluZyI6eyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9Db2RlU3lzdGVtL2VwYS1kcnVnLWNhdGVnb3J5LWNzIiwiY29kZSI6IjAwIn19LHsidXJsIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vU3RydWN0dXJlRGVmaW5pdGlvbi9tZWRpY2F0aW9uLWlkLXZhY2NpbmUtZXh0ZW5zaW9uIiwidmFsdWVCb29sZWFuIjpmYWxzZX0seyJ1cmwiOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9TdHJ1Y3R1cmVEZWZpbml0aW9uL3J4LXByZXNjcmlwdGlvbi1wcm9jZXNzLWlkZW50aWZpZXItZXh0ZW5zaW9uIiwidmFsdWVJZGVudGlmaWVyIjp7InN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL3NpZC9yeC1wcmVzY3JpcHRpb24tcHJvY2Vzcy1pZGVudGlmaWVyIiwidmFsdWUiOiIxNjAuMDAwLjEwNi44NzguMjQwLjk4XzIwMjUwMjE3In19XSwiY29kZSI6eyJjb2RpbmciOlt7InN5c3RlbSI6Imh0dHA6Ly9maGlyLmRlL0NvZGVTeXN0ZW0vaWZhL3B6biIsImNvZGUiOiIwMDI5NDYzOSJ9XSwidGV4dCI6IlBhbnRvcHJhem9sIEJpb21vIDIwbWcgMTUgU1QifSwiZm9ybSI6eyJjb2RpbmciOlt7InN5c3RlbSI6Imh0dHBzOi8vZmhpci5rYnYuZGUvQ29kZVN5c3RlbS9LQlZfQ1NfU0ZISVJfS0JWX0RBUlJFSUNIVU5HU0ZPUk0iLCJjb2RlIjoiVE1SIn1dfSwiYW1vdW50Ijp7Im51bWVyYXRvciI6eyJleHRlbnNpb24iOlt7InVybCI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vbWVkaWNhdGlvbi1wYWNrYWdpbmctc2l6ZS1leHRlbnNpb24iLCJ2YWx1ZVN0cmluZyI6IjEifV0sInVuaXQiOiJQYWtldCIsInN5c3RlbSI6Imh0dHA6Ly91bml0c29mbWVhc3VyZS5vcmciLCJjb2RlIjoie1BhY2thZ2V9In0sImRlbm9taW5hdG9yIjp7InZhbHVlIjoxfX0sImlkZW50aWZpZXIiOlt7InN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL3NpZC9lcGEtbWVkaWNhdGlvbi11bmlxdWUtaWRlbnRpZmllciIsInZhbHVlIjoiRjMxNkZDRkM1NUE3NTAxMzg4MDg1RjQ1NDkzMUM2RDVERDAyRTYwNzczQUQyRjExODg0MkM5QjYyQzM5QkE4OSJ9LHsic3lzdGVtIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vc2lkL3J4LW9yaWdpbmF0b3ItcHJvY2Vzcy1pZGVudGlmaWVyIiwidmFsdWUiOiJmZDQxMTE2OS00MjA2LTRkZmUtOTZjOC1lM2JmYjkyYzA3Y2JfMTYwLjAwMC4xMDYuODc4LjI0MC45OCJ9XSwic3RhdHVzIjoiaW5hY3RpdmUifSwic2VhcmNoIjp7Im1vZGUiOiJtYXRjaCJ9fSx7ImZ1bGxVcmwiOiJodHRwOi8vZXBhNGFsbC9lcGEvbWVkaWNhdGlvbi9hcGkvdjEvZmhpci9NZWRpY2F0aW9uUmVxdWVzdC83MjJiNzkwNC1jZDJlLTRmZDktYmYxOS0xYjQ0ZWY1YWU4MGUiLCJyZXNvdXJjZSI6eyJyZXNvdXJjZVR5cGUiOiJNZWRpY2F0aW9uUmVxdWVzdCIsImlkIjoiNzIyYjc5MDQtY2QyZS00ZmQ5LWJmMTktMWI0NGVmNWFlODBlIiwibWV0YSI6eyJwcm9maWxlIjpbImh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vZXBhLW1lZGljYXRpb24tcmVxdWVzdHwxLjAuMyJdLCJsYXN0VXBkYXRlZCI6IjIwMjUtMDItMTdUMDk6NDc6MjcuNDIxMTM5WiJ9LCJleHRlbnNpb24iOlt7InVybCI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL2VwYS1tZWRpY2F0aW9uL1N0cnVjdHVyZURlZmluaXRpb24vbXVsdGlwbGUtcHJlc2NyaXB0aW9uLWV4dGVuc2lvbiIsImV4dGVuc2lvbiI6W3sidXJsIjoiaW5kaWNhdG9yIiwidmFsdWVCb29sZWFuIjpmYWxzZX1dfV0sInN0YXR1cyI6ImFjdGl2ZSIsImludGVudCI6ImZpbGxlci1vcmRlciIsIm1lZGljYXRpb25SZWZlcmVuY2UiOnsicmVmZXJlbmNlIjoiTWVkaWNhdGlvbi9mYzQ2NDUxZC02YWY4LTRhZmItODgwYy01MTA0ZDdhYmFkODMifSwic3ViamVjdCI6eyJpZGVudGlmaWVyIjp7InN5c3RlbSI6Imh0dHA6Ly9maGlyLmRlL3NpZC9na3Yva3ZpZC0xMCIsInZhbHVlIjoiWDExMDYyNDAwNiJ9fSwiYXV0aG9yZWRPbiI6IjIwMjUtMDItMTciLCJkb3NhZ2VJbnN0cnVjdGlvbiI6W3sidGV4dCI6IjAtMS0wIn1dLCJkaXNwZW5zZVJlcXVlc3QiOnsicXVhbnRpdHkiOnsidmFsdWUiOjEsInN5c3RlbSI6Imh0dHA6Ly91bml0c29mbWVhc3VyZS5vcmciLCJjb2RlIjoie1BhY2thZ2V9In19LCJzdWJzdGl0dXRpb24iOnsiYWxsb3dlZEJvb2xlYW4iOnRydWV9LCJpZGVudGlmaWVyIjpbeyJzeXN0ZW0iOiJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEtbWVkaWNhdGlvbi9zaWQvcngtcHJlc2NyaXB0aW9uLXByb2Nlc3MtaWRlbnRpZmllciIsInZhbHVlIjoiMTYwLjAwMC4xMDYuODc4LjI0MC45OF8yMDI1MDIxNyJ9LHsic3lzdGVtIjoiaHR0cHM6Ly9nZW1hdGlrLmRlL2ZoaXIvZXBhLW1lZGljYXRpb24vc2lkL3J4LW9yaWdpbmF0b3ItcHJvY2Vzcy1pZGVudGlmaWVyIiwidmFsdWUiOiIwMzViY2Y0Yy1hZmM2LTRmN2QtYjMxNy00NjdmY2U3NDJiMGVfMTYwLjAwMC4xMDYuODc4LjI0MC45OCJ9XSwicmVxdWVzdGVyIjp7InJlZmVyZW5jZSI6IlByYWN0aXRpb25lclJvbGUvYjEzY2QxMmEtY2YwMC00ZTdkLWFiZmItYjQ3YzY1NTYxNmRkIn19LCJzZWFyY2giOnsibW9kZSI6Im1hdGNoIn19LHsiZnVsbFVybCI6Imh0dHA6Ly9lcGE0YWxsL2VwYS9tZWRpY2F0aW9uL2FwaS92MS9maGlyL1Byb3ZlbmFuY2UvMDE5YzFlOTItNDU3Ni03MmJlLTgwZjctNDg5ZmQ4YzJlOWYyIiwicmVzb3VyY2UiOnsiYWN0aXZpdHkiOnsiY29kaW5nIjpbeyJjb2RlIjoiQ1JFQVRFIiwiZGlzcGxheSI6ImNyZWF0ZSIsInN5c3RlbSI6Imh0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL0NvZGVTeXN0ZW0vdjMtRGF0YU9wZXJhdGlvbiJ9XX0sImFnZW50IjpbeyJ0eXBlIjp7ImNvZGluZyI6W3siY29kZSI6ImF1dGhvciIsImRpc3BsYXkiOiJBdXRob3IiLCJzeXN0ZW0iOiJodHRwOi8vdGVybWlub2xvZ3kuaGw3Lm9yZy9Db2RlU3lzdGVtL3Byb3ZlbmFuY2UtcGFydGljaXBhbnQtdHlwZSJ9XX0sIndobyI6eyJpZGVudGlmaWVyIjp7InN5c3RlbSI6Imh0dHBzOi8vZ2VtYXRpay5kZS9maGlyL3NpZC9lcGEtZmhpci1kYXRhLXNlcnZpY2UiLCJ2YWx1ZSI6Ik1FRElDQVRJT05TVkMifX19XSwiaWQiOiIwMTljMWU5Mi00NTc2LTcyYmUtODBmNy00ODlmZDhjMmU5ZjIiLCJtZXRhIjp7Imxhc3RVcGRhdGVkIjoiMjAyNi0wMi0wMlQxMzozNzowOC40NzA3MDlaIiwicHJvZmlsZSI6WyJodHRwczovL2dlbWF0aWsuZGUvZmhpci9lcGEvU3RydWN0dXJlRGVmaW5pdGlvbi9lcGEtYWN0aXZpdHktcHJvdmVuYW5jZXwxLjMuMCJdLCJ2ZXJzaW9uSWQiOiIxIn0sInJlY29yZGVkIjoiMjAyNi0wMi0wMlQxMzozNzowOC40NzA3MjNaIiwicmVzb3VyY2VUeXBlIjoiUHJvdmVuYW5jZSIsInRhcmdldCI6W3sicmVmZXJlbmNlIjoiTWVkaWNhdGlvblN0YXRlbWVudC8wMTljMWU5Mi00NTVhLTcxM2MtODBjOC1kNWFiNWNmZjE5NTUvX2hpc3RvcnkvMSJ9XX0sInNlYXJjaCI6eyJtb2RlIjoibWF0Y2gifX1dfQo=";
            String selectedMedicationId = "b9061dcf-ae00-472c-82b5-d8f29104b35c";

            given()
                .queryParams(Map.of(X_KONNEKTOR, "localhost"))
                .queryParams(Map.of(X_INSURANT_ID, kvnr))
                .body(new EPrescriptionKimSender.EPrescriptionRequest(
                    epaBundleBase64,
                    selectedMedicationId,
                    positiveFlow ? practitionerName : "wrongSearch"
                ))
                .contentType(APPLICATION_JSON)
                .when()
                .post("/e-prescription-kim-sender")
                .then()
                .body(containsString(expectedBodyPart))
                .statusCode(expectedStatus);
        }
    }

    @Test
    public void equipmentSentToKim() throws Exception {
        String telematikId = "1-SMC-B-Testkarte--883110000162363";
        String kvnr = "X110587452";
        prepareInsurantFiles(telematikId, kvnr);

        String equipment = "TRACHEOFIRST® PRO; Art.-Nr.: 67800";
        given()
            .queryParams(Map.of(X_KONNEKTOR, "localhost"))
            .queryParams(Map.of(X_INSURANT_ID, kvnr))
            .body(new EquipmentPrescription.PrescriptionDto(
                equipment,
                "lanr",
                "prefix",
                "bsnr",
                "+491736322621",
                "Hallo Apotheke!"
            ))
            .contentType(APPLICATION_JSON)
            .when()
            .post("/prescription")
            .then()
            .body(containsString("OK"))
            .statusCode(200);

        assertReceivedContent(equipment);
    }

    private void assertReceivedContent(String expected) throws Exception {
        greenMail.waitForIncomingEmail(1);
        Message[] messages = greenMail.getReceivedMessages();
        assertEquals(1, messages.length);
        Message message = messages[0];
        assertEquals(kimConfig.getSubject(), message.getSubject());
        if (message.getContent() instanceof Multipart multipart) {
            BodyPart part = multipart.getBodyPart(1);
            String body = (String) part.getContent();
            assertTrue(body.contains(expected));
        }
    }
}